# Generated by Django 4.1.2 on 2023-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut_nome', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_alcunha', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_data_nasc', models.DateField(blank=True, null=True)),
                ('aut_idade', models.IntegerField(blank=True, null=True)),
                ('aut_fx_etaria', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_nro_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_tipo_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_pai', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_mae', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_tipo', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_sexo', models.CharField(blank=True, max_length=500, null=True)),
                ('grau_de_relacionamento', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_cor_pele', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_grau_inst', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_profissao', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_sit_emprego', models.CharField(blank=True, max_length=500, null=True)),
                ('aut_est_civil', models.CharField(blank=True, max_length=500, null=True)),
                ('qtd_autor', models.IntegerField(blank=True, null=True)),
                ('meio_emp_deac', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sicadfull',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
