# Generated by Django 4.1.2 on 2023-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_alter_sicadfull_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicadfull',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
