# Generated by Django 4.1.2 on 2023-05-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_alter_sicadfull_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sicadfull',
        ),
    ]
